Metrowerks overhaul
projectPiki/pikmin2 pull request #164
Opened 2023-04-21 15:49 UTC by CelestialAmber

-Make MSL_C match under inline deferred
-Overhaul metrowerks header files

You're very welcome

2023-04-21 16:22 UTC, kiwi515 commented on src/Dolphin/MSL_C/arith.c
> +	return (__x >> 0x1f ^ __x) - (__x >> 0x1f);
Does `x > 0 ? x : -x` match here?

2023-04-21 16:48 UTC, EpochFlame requested changes
Quite a few of these files are missing the ending newlines- we should fix that before merging. Thank you for the overhaul.

2023-04-21 21:21 UTC, EpochFlame approved these changes

2023-04-21 23:15 UTC, CelestialAmber commented on src/Dolphin/MSL_C/arith.c
> +	return (__x >> 0x1f ^ __x) - (__x >> 0x1f);
It does thankfully

2023-04-22 06:25 UTC, CelestialAmber commented
I think I'm done for now. If you really want I can get myself to do the remaining 5 files, but I kind of feel like just keeping this PR as is and doing that in another PR.

2023-04-22 06:36 UTC, EpochFlame approved these changes
lgtm

2023-04-22 06:37 UTC, merged